-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- Prices Table
create table if not exists prices (
  id text primary key,
  "userId" text,
  "productName" text not null,
  price float not null,
  supermarket text not null,
  quantity text,
  timestamp text not null,
  barcode text,
  brand text,
  "imageUrl" text,
  latitude float,
  longitude float,
  address text
);

-- Users Table
create table if not exists users (
  id text primary key,
  "displayName" text not null,
  "avatarId" text not null,
  "joinedDate" text not null,
  "pricesShared" integer default 0,
  "totalSavings" float default 0
);

-- Products Table (Cache)
create table if not exists products (
  barcode text primary key,
  name text not null,
  brand text,
  "imageUrl" text,
  "createdAt" text not null
);

-- Supermarkets Table
create table if not exists supermarkets (
  id bigint generated by default as identity primary key,
  name text not null unique,
  type text,
  address text,
  latitude float,
  longitude float
);

-- Seed Supermarkets (Optional - based on existing data)
insert into supermarkets (name, type, address) values
('Zumica Supermercado', 'Supermarket', 'Av. Davi Alves Silva, 495 – Centro'),
('Mateus Supermercados', 'Supermarket', 'Rua Divino Espírito Santo – Vila Mansueto'),
('Mundo Atacado (Mundô Supermercado)', 'Supermarket', 'Av. Davi Alves Silva, 820 – Colégio Agrícola'),
('Supermercado Bom Preço', 'Supermarket', 'Rua da Paz, 72 – Vila Davi'),
('Sacolão Econômico', 'Fruit Store/Sacolão', 'BR-222 (rodovia) – Buriticupu'),
('Atacadão das Frutas', 'Fruit Store/Sacolão', 'BR-222, km 554, s/n – Buritizinho area'),
('Mercado União', 'Small Market', 'Av. Davi Alves Silva, 599 – Centro'),
('Mercadinho Jb', 'Small Market', 'Rua 244 – Terra Bela'),
('Mercadinho Marques', 'Small Market', 'Av. 20 – Eco II'),
('Mercadinho Menor Preço', 'Small Market', 'Rua 220 – Terra Bela'),
('Mercadinho Mix Davi', 'Small Market', 'Rua 08 – Letra A – Vila Primo'),
('Mercadinho Rodrigues', 'Small Market', 'Rua 21 – Armz – Terra Bela'),
('Mercantil J. Rezende', 'Small Market', 'Zona Rural – Buriticupu'),
('Mercantil Mateuzin', 'Small Market', 'Av. 343 – Centro'),
('Mercantil Oliveira', 'Small Market', 'Rua 537 – Armz – Centro'),
('Mercearia Moraes', 'Small Market', 'Rua 14 – Vila Cajueiro'),
('Supermercado Wonanth', 'Supermarket', 'Rua Cafeteira, 115 – Buriticupu'),
('Depósito Vale Buriti', 'Supermarket', 'Av. Davi Alves Silva – Buriticupu'),
('Solange M. C. Brito Supermercados', 'Supermarket', 'Rua Dom Pedro I – Centro'),
('Comercial Johnattan', 'Supermarket', 'Av. Castelo Branco – Buriticupu')
on conflict (name) do nothing;
