export interface PriceLocation {
  latitude: number;
  longitude: number;
  address?: string;
}

export interface Price {
  id: string;
  userId?: string;
  productName: string;
  price: number;
  supermarket: string;
  /** e.g. "1kg", "500ml" */
  quantity?: string;
  timestamp: string;
  barcode?: string;
  brand?: string;
  imageUrl?: string;
  location?: PriceLocation;
}

/** Used when registering a new price — id is generated by the use case */
export type NewPrice = Omit<Price, 'id'>;
